import type { UserSettings } from "./UserSettings";

export const DefaultSettings: UserSettings = {
  locations: {
    name: true,
    address: true,
    recommended: true,
    purchaseCount: true,
    percentage: true,
    notes: false
  },
  playlogs: {
    date: true,
    listeners: true,
    artist: true,
    album: true,
    notes: false
  },
  vinyls: {
    purchaseNumber: true,
    artist: true,
    album: true,
    color: false,
    purchaseDate: false,
    purchaseLocation: false,
    owners: true,
    purchasedBy: false,
    likedBy: false,
    notes: false,
    doubleLP: false,
    isComplete: false,
    length: false,
    playCount: false,
    price: false,
    tags: false,
  },
  wantedItems: {
    artist: true,
    album: true,
    imageUrl: true,
    searcher: true,
    created_at: false,
    weight: true,
    notes: false
  },
  currentStatsTab: "1",
  userStatsSectionOrder: ["vinyls", "topArtists", "locations", "playlogs", "topPlayDays", "playsByDays", "playsByTimelineChart", "playsByAlbum", "playsByArtist"],
  houseStatsSectionOrder: ["vinyls", "topArtists", "locations", "playlogs", "topPlayDays", "playsByDays", "playsByTimelineChart", "playsByAlbum", "playsByArtist"],
  userStatsExpandedSections: {
    userStats: true,
    vinyls: true,
    topArtists: true,
    locations: true,
    playlogs: true,
    topPlayDays: true,
    playsByDays: true,
    playsByTimelineChart: true,
    playsByAlbum: true,
    playsByArtist: true,
  },
  houseStatsExpandedSections: {
    houseStats: true,
    vinyls: true,
    topArtists: true,
    locations: true,
    playlogs: true,
    topPlayDays: true,
    playsByDays: true,
    playsByTimelineChart: true,
    playsByAlbum: true,
    playsByArtist: true,
  },
  pricePerPlayValue: false,
  sortModels: {
    locations: [{ field: 'name', sort: 'asc' }],
    playlogs: [{ field: 'playNumber', sort: 'desc' }],
    vinyls: [{ field: 'purchaseNumber', sort: 'desc' }],
    wantedItems: [{ field: 'artist', sort: 'asc' }],
  },
  tableColumnOrders: {
    locations: [],
    playlogs: [],
    vinyls: [],
    wantedItems: [],
  },
  statsStartDate: new Date().toISOString(),
  pageSize: 25
}